- name: variables to print
  hosts: web
  vars: 
   COURSE: "DEVOPS WITH AWS"
   DURATION: "120HRS"
   TRAINER: "LAXMI"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi I am learning Course {{COURSE}},Duration is {{DURATION}}, {{TRAINER}} "