- name: variables to print
  hosts: web
  vars: #play level, all tasks in this pplay have access to this
   COURSE: "DEVOPS WITH AWS"
   DURATION: "120HRS"
   TRAINER: "LAXMI"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi I am learning Course {{COURSE}},Duration is {{DURATION}},and Trainer is {{TRAINER}} "


  - name: print the information
    vars: 
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi I am learning Course {{COURSE}},Duration is {{DURATION}},and Trainer is {{TRAINER}} "

  - name: print the information
    ansible.builtin.debug:
      msg: "Hi I am learning Course {{COURSE}},Duration is {{DURATION}},and Trainer is {{TRAINER}} "