- name: variables from file
  hosts: web
  vars_files:
  - vars.yaml
  tasks: 
  - name: print the coourse info
     ansible.builtin.debug:
     msg: "Hi I am learning Course {{COURSE}},Duration is {{DURATION}},and Trainer is {{TRAINER}} "