- name: variable to print
  host: local
  connection: local
  become: yes
  tasks:
  - name: print the information
    vars
      DURATION: "120"
      TRAINER: "Laxmi"
    ansible.builtin.debug:
     msg: " Hi I am learning {{ COURSE }}"