- name: install nginx
  hosts: web
  tasks:
  - name: install packages
    ansible.builtin.package:
     name:  "{{ item }}""
     state: present
    loop:
    - ramesh
    - suresh
    - ram
    - sita