- name: filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
     msg: "Hello {{ course | default ('Ansible') }}"

  - name: conver to uppercase
    vars:
      greeting: "Hello devops"
    ansible.builtin.debug:
     msg: " {{ greeting | upper }}"
  
  - name: convert to lower
    vars:
     greeting: "HELLO DEVOPS"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"

  - name: finding the unique values
    vars:
     numbers: [ 1, 2, 3, 3, 4,6,8,1]
    ansible.builtin.debug:
     msg: " {{ numbers | unique }}"
  
  - name: finding min and max numbers
    vars:
     numbers: [ 1, 33, 83, 223, 4,6,8,1]
    ansible.builtin.debug:
     msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: map to list
    vars: 
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "Laxmi"
    ansible.builtin.debug:
      msg: " {{ course | dict2items }}"
  
  - name: list to map
    vars:
     course:
     - { "key": "name","value": "DevOps with AWS" }
     - { "key": "duration","value": 120 }
     - { "key": "trainer","value": "laxmi" }
    ansible.builtin.debug:
      msg: " {{ course | items2dict }}"

  - name: check ip address
    vars:
      myip: "123.456.2.4"
    ansible.builtin.debug:
     msg: "{{ myip | ansible.utils.ipv4 }}"
  